fragment ServicesParts on Services {
  __typename
  title
  description
  priceRange
  category
  icon
  image
  order
  body
}

fragment PagesParts on Pages {
  __typename
  title
  description
  body
}

fragment LocationsParts on Locations {
  __typename
  title
  address
  postalCode
  city
  phone
  email
  openingHours {
    __typename
    weekdays
    saturday
    sunday
  }
  body
}

fragment TestimonialsParts on Testimonials {
  __typename
  name
  location
  rating
  date
  body
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  title
  images {
    __typename
    logo
    heroImage
    teamPhotoMain
    clinicInteriorGeneral
    placeholderGeneral
    homepageHero
    homepageTeamLarge
    homepageEquipment1
    homepageEquipment2
    homepageEquipment3
    solheimHeroInterior
    solheimTreatmentRoom
    solheimEquipment
    solheimExterior
    solheimReception
    solheimWaitingRoom
    paradisHeroInterior
    paradisTreatmentRoom
    paradisEquipment
    paradisExterior
    paradisReception
    paradisWaitingRoom
    emergencyCare
    painRelief
    emergencyEquipment
    contactHero
    anxietyTreatment
    aboutHeroTeam
    aboutClinicShowcase
    aboutEquipment
    treatmentsHero
  }
  body
}
